#!/bin/bash
#PBS -N savsrware                 # Job name
#PBS -m bea                               # Mail on (b)egin, (e)nd, and (a)bort (fail)
#PBS -M savitha@comp.nus.edu.sg          # Email address for notifications
#PBS -l walltime=120:00:00                # 5 days walltime
#PBS -q ai                              # Queue name (partition equivalent in PBS)
#PBS -j oe                                # Combine stdout and stderr into a single file

# Load environment and activate conda
source ~/.bashrc
conda activate ft-gym-env

# Change to the directory where the job was submitted from
cd $PBS_O_WORKDIR

# Run the training script (uncomment the one you want to use)
# python src/main.py --config=mappo --env-config=sc2 with env_args.map_name="2s_vs_1sc"
# python src/main.py --config=maa2c --env-config=gymma with env_args.time_limit=500 env_args.key="rware:rware-tiny-2ag-v2"
# python src/main.py --config=qmix --env-config=gymma with env_args.time_limit=500 env_args.key="rware:rware-tiny-2ag-v2"
# python src/main.py --config=coma  --env-config=gymma with env_args.time_limit=25 env_args.key="pz-mpe-simple-adversary-v3" env_args.pretrained_wrapper="PretrainedAdversary"
# python src/main.py --config=maddpg --env-config=gymma with env_args.time_limit=50 env_args.key="lbforaging:Foraging-8x8-2p-3f-v3"
python src/main.py --config=mappo_rware --env-config=gymma with env_args.time_limit=500 env_args.key="rware:rware-tiny-4ag-v2"
# python src/main.py --config=maa2c_rware --env-config=gymma with env_args.time_limit=500 env_args.key="rware:rware-tiny-4ag-v2"
